services:
  # Single Service: Backend serves Frontend
  - type: web
    name: stylehub
    runtime: node
    plan: free
    region: singapore
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Add this manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false  # Add this manually
      - key: RAZORPAY_KEY_SECRET
        sync: false  # Add this manually

